### ISSUE TITLE
Inconsist way to specify network between OpenStackcluster and OpenStackMachineTemplate

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#1067]
/kind bug

**What steps did you take and what happened:**

When I use existing network, I had to write a little different way to specify the network.

OpenStackCluster:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: OpenStackCluster
metadata:
  name: external
  namespace: default
spec:
  network:
    name: selfservice
```

OpenStackMachineTemplate:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: OpenStackMachineTemplate
metadata:
  name: external-control-plane
  namespace: default
spec:
  template:
    spec:
      networks:
      - filter:
          name: selfservice
```

The spec of `OpenStackMachineTemplate` needs `filter`.

**What did you expect to happen:**

I expect to write them in the same manner.

**Anything else you would like to add:**

I find this issue in the discussion: https://kubernetes.slack.com/archives/CFKJB65G9/p1637178119109300

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.5.0
- Cluster-API version: 1.0.0
- OpenStack version: Stein
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by mdbooth** [comment]
I think the fundamental difference here is that in the cluster you're specifying a network, but in the machine you're specifying a port on a network, hence it has additional parameters and the network filter is only one of them. That said, the machine network parameter is janky, hence @iamemilio is working on #1059. The machine network parameter should go away in favour of the ports parameter, which should make the difference clearer.

You could also specify [1]:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: external-control-plane
  namespace: default
spec:
  template:
    spec:
      ports:
      - networkId: <id of selfservice>
```

With @iamemilio's PR that would become:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: external-control-plane
  namespace: default
spec:
  template:
    spec:
      ports:
      - network:
        - name: selfservice
```

With PR #1059, clusterspec.network and machinespec.ports.network both use NetworkFilter. Is this the consistency you're looking for?

[1] If you choose to specify the network in the machinespec at all, which you don't have to if you only want a single port.

**Comment by hidekazuna** [comment]
@mdbooth That is not exactly what I am looking for. I wondered if I could specify port of the network "without specifying port"  when I create a cluster using only one network:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: external-control-plane
  namespace: default
spec:
  template:
    spec:
       networks:
        - name: selfservice
```

On the other side It also makes sense the machine network parameter goes away to make the difference clearer. I think accepting both is unnecessarily complicated. Let's take @iamemilio's PR.
