### ISSUE TITLE
Mandatory Tags field for trunk setup

### ISSUE THREAD

**Issue by Xenwar** [kubernetes-sigs/cluster-api-provider-openstack#1106]
When enabling trunk at port or instance level without tags field, provisioning a CP node is not possible for the following reason.

`E0104 10:21:04.379852       9 controller.go:317] controller/openstackmachine "msg"="Reconciler error" "error"="error creating Openstack instance: Missing input for argument [Tags]" "name"="basic-1-control-plane-jv45x" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine" `

However, if tags field is introduced, tests pass and deployment continues.

```
      ports:
      - description: "primary with PortSecurity enabled, required for proper k8s cluster"
        disablePortSecurity: false
        trunk: true
        tags:
        - "tag1"
        allowedAddressPairs:
        - macAddress: "a4:b8:34:2b:ab:01"
          ipAddress: "10.10.10.10/24"
```

/kind bug
