### ISSUE TITLE
Root volume source UUID is incorrectly mapped to image instead of imageUUID in CRD conversion

### ISSUE THREAD

**Issue by tfussell** [kubernetes-sigs/cluster-api-provider-openstack#1220]
/kind bug

**What steps did you take and what happened:**

I upgraded my self-managed management cluster from CAPO v0.5.3 to a pre-release build of v0.6.0 based on the `main` branch. Following this upgrade, scaling up the worker MachineDeployment resulted in newly created `OpenStackMachine`s in a `Failed` state due to the following error:

```yaml
status:
  failureMessage: 'OpenStack instance cannot be created: error creating Openstack
    instance: error getting image ID: no image with the Name 4ebeedcf-c2db-41b5-8d33-7cbc324e0926
    could be found'
  failureReason: UpdateError
```

**What did you expect to happen:**

I expected `OpenStackMachine`s using a `rootVolume` and a `v1alpha4` `OpenStackMachineTemplate` to start normally when using CAPO v0.6.0.

**Anything else you would like to add:**

The error message indicates that the name doesn't exist, but we use root volumes with source UUIDs so the image should be referred to by UUID rather than by name. I believe there is a mistake in the CRD conversion logic mapping `v1alpha4`'s `.spec.rootVolume.sourceUUID` to `v1alpha5`'s `.spec.image` instead of `.spec.imageUUID`.

This code can be found in several places such as https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/api/v1alpha4/conversion.go#L274.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): `88901897ee2bbd7b9440d5e73db9aea15f4fdf49`
- Cluster-API version: 1.1.3
- OpenStack version: ?
- Minikube/KIND version: Permanent cluster, not using kind
- Kubernetes version (use `kubectl version`): client 1.23.3, server 1.22.8
- OS (e.g. from `/etc/os-release`): `Ubuntu 20.04.4 LTS`
