### ISSUE TITLE
Specify security groups by name at Port level

### ISSUE THREAD

**Issue by Xenwar** [kubernetes-sigs/cluster-api-provider-openstack#1245]
As a user, I would like to specify security groups by name instance creation time.

As we have it now, it is possible to specify security groups at `port level `using uuids. However, the instance level setting is more flexible in that it allows specifying security groups using other parameters as shown below. 

```
kubectl explain OpenStackMachineTemplate.spec.template.spec.securityGroups
KIND:     OpenStackMachineTemplate
VERSION:  infrastructure.cluster.x-k8s.io/v1alpha5
RESOURCE: securityGroups <[]Object>
DESCRIPTION:
     The names of the security groups to assign to the instance
FIELDS:
   filter       <Object>
     Filters used to query security groups in openstack
   name <string>
     Security Group name
   uuid <string>
     Security Group UID
```
It would be useful if this feature is also added at port level. 
This can be archived by adding a new field in order to support backward compatibly. A sample template is shown below. 

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackMachineTemplate
metadata:
  name: basic-1-md-0
  namespace: default
spec:
  template:
    spec:
      securityGroups:
      - name: capo-instance-level-sg
      ports:
      - description: "Port 1 with security group"
        securityGroups: # old field, left for backward compatiblity
        - "2f6584db-5138-453b-b47b-99696cb11f0f" 
        securityGroupsFilters: # the new field
        - name: "capo-port-level-sg" # Security Group name
      cloudName: openstack-1
      flavor: 2C-4GB-100GB
```

/kind feature
