### ISSUE TITLE
Network filter not properly filtering

### ISSUE THREAD

**Issue by justapill** [kubernetes-sigs/cluster-api-provider-openstack#1387]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

In my environment, we have pre-defined networks for internal traffic between the nodes; a network and subnet. Nodecidr is not defined. The error on capo-controller-manager is failing to reconcile the k8s cluster resource, it's possible this is user error as this is the first time I've used cluserAPI as a deployment method for k8s. The error prints out all of the network names that we have in our openstack project, except the one that is specified in the network filter in the following yaml. 

here's the yaml I'm using for a machinetemplate,

```apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackMachineTemplate
metadata:
  name: capi-openstack-0-md-0
  namespace: default
spec:
  template:
    spec:
      cloudName: openstack
      flavor: k8s-worker
      identityRef:
        kind: Secret
        name: capi-openstack-0-cloud-config
      image: ubuntu-2004-kube-v1.23.10
      sshKeyName: k8skey
      networks:
      - filter:
          name: VLAN<redacted>
          id: <redacted>
        subnets:
        - filter:
            name: <redacted>`
```
Error:
`E1118 19:37:07.491376       1 controller.go:317] controller/openstackcluster "msg"="Reconciler  │
│ error" "error"="failed to find only one network `

**What did you expect to happen:**
Cluster to reconcile with specified network filter.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
As a side note `subnet_id` mentioned in the docs here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/docs/book/src/clusteropenstack/configuration.md#multiple-networks

Is returning as an invalid value.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v1.2.5
- Cluster-API version:  v0.6.4
- OpenStack version: wallaby
- Minikube/KIND version: v0.16.0
- Kubernetes version (use `kubectl version`): v1.25.2
- OS (e.g. from `/etc/os-release`): ubuntu 22.04.1 LTS

**Comment by jichenjc** [comment]
I think from code 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/controllers/openstackcluster_controller.go#L449

your filter should makes CAPO find one and only one network otherwise the error report

>>>The error prints out all of the network names that we have in our openstack project, except the one that is specified in the network filter in the following yaml.


so you need check how many networks you are having and with filter , what's left, with that, it might helps fix the issue

**Comment by justapill** [comment]
> I think from code https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/controllers/openstackcluster_controller.go#L449
> 
> your filter should makes CAPO find one and only one network otherwise the error report
> 
> > > > The error prints out all of the network names that we have in our openstack project, except the one that is specified in the network filter in the following yaml.
> 
> so you need check how many networks you are having and with filter , what's left, with that, it might helps fix the issue

Is there a way to check the network filter before deploying in kind? How is CAPO filtering for the network?

I've also tried using the `uuid` parameter with the same results. 

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackMachineTemplate
metadata:
  name: <cluster-name>-controlplane
  namespace: <cluster-name>
spec:
  networks:
  - uuid: your_network_id
  ```
  (pulled from docs)

**Comment by jichenjc** [comment]
check above logic I mentioned, it will call `GetNetworksByFilter` (there are some wrapper calls inside CAPO)

and finally go to https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/networks/requests.go#L49

I think your uuid try is incorrect per 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/api/v1alpha6/types.go#L70

so please keep id+name combination, and from above logic, the filter will use those input (id+name) and filter network from list

**Comment by justapill** [comment]
I've given the filter as much info as I can,
```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackMachineTemplate
metadata:
  name: capi-openstack-0-md-0
  namespace: default
spec:
  template:
    spec:
      cloudName: openstack
      flavor: k8s-worker
      identityRef:
        kind: Secret
        name: capi-openstack-0-cloud-config
      image: ubuntu-2004-kube-v1.23.10
      sshKeyName: k8skey
      networks:
      - uuid: <redacted>
      - filter:
          name: VLAN<redacted>
          id: <redacted>
          projectId: <redacted>
        subnets:
        - filter:
            name: SVCS-K8S-INT
            id: <redacted>
            projectId: <redacted>
            cidr: <redacted>
            ipVersion: 4
            gateway_ip: <redacted>
```
Here's a snippet of the trace `2022-01-12 20:11:37 +0000 UTC 8a691630371549cdb42159d62710cadf false [] []} {<network_id> VLAN<redacted>  true ACTIVE [<subnet_id>] <project_id>` 
All of networks are listed in the trace even ones not in the specified project id. Except the network I'm filtering for.
I'm beginning to think it's a domain configuration thing. We have all of our networks in one domain and segregated by project, and not by domain. 
e.g. When I use the openstack cli tool to list our networks all of them are listed, even though I have a project id specified in the clouds.yml
