### ISSUE TITLE
Pass user data to machine in the form of secret

### ISSUE THREAD

**Issue by flaper87** [kubernetes-sigs/cluster-api-provider-openstack#158]
As of now, the userData we pass to the machine corresponds to the startUp script. However, it should be possible to override/pass the userData to the machine config in the form of secret. For example:

```
items:
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    generateName: openstack-master-
    labels:
      set: master
  spec:
    providerSpec:
      value:
        apiVersion: "openstackproviderconfig/v1alpha1"
        kind: "OpenstackProviderSpec"
        flavor: m1.medium
        image: ...
        sshUserName: ...
        availabilityZone: nova
        networks:
        - uuid: ...
        floatingIP: 129.114.111.153
        securityGroups:
        - default
        userDataSecret: $secret-name
    versions:
      kubelet: 1.12.3
      controlPlane: 1.12.3
```
This way we can do away with serializing and mounting the startup script into the CAPO pod.
