### ISSUE TITLE
When defining additionalPorts under apiServerLoadBalancer no security group rule is created (port opening)

### ISSUE THREAD

**Issue by huxcrux** [kubernetes-sigs/cluster-api-provider-openstack#1588]
/kind bug

**What steps did you take and what happened:**
When defining additionalPorts under apiServerLoadBalancer in the OpenStackCluster manifest no security group rule is created meaning the LB will not reach the requested port.

**What did you expect to happen:**
All ports added to additionalPorts to also have a corresponding security group rule added

**Anything else you would like to add:**

Sample manifest:
```yaml
apiVersion: v1
items:
- apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
  kind: OpenStackCluster
  metadata:
    labels:
      cluster.x-k8s.io/cluster-name: hux-lab1
    name: hux-lab1
  spec:
    allowAllInClusterTraffic: true
    apiServerLoadBalancer:
      additionalPorts:
      - 31991
      enabled: true
    cloudName: elastx
    controlPlaneEndpoint:
      host: REDACTED
      port: 6443
    disableAPIServerFloatingIP: false
    dnsNameservers:
    - 8.8.8.8
    - 4.4.4.4
    externalNetworkId: 600b8501-78cb-4155-9c9f-23dfcba88828
    identityRef:
      kind: Secret
      name: hux-lab1-cloud-config
    managedSecurityGroups: true
    network: {}
    nodeCidr: 10.128.0.0/22
    subnet: {}
```

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): 0.7.3
- Cluster-API version: 0.4.3
- OpenStack version: Ussuri
- Minikube/KIND version: Kind 0.17.0
- Kubernetes version (use `kubectl version`): 1.26.4 (also tested 1.27.2)
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04
