### ISSUE TITLE
Use standard clouds.yaml file as config file

### ISSUE THREAD

**Issue by flaper87** [kubernetes-sigs/cluster-api-provider-openstack#16]
We're currently using a custom config file for `cluster-api-provider-openstack`, which is different from both, the `cloud-provider-openstack` config file and the [standard `clouds.yaml` file](https://docs.openstack.org/python-openstackclient/pike/configuration/index.html). The current config uses the following format:

```
user-name:
password: 
domain-name: 
tenant-id: 
region:
auth-url:
```
In order to provider a better user experience, it'd be better to either adopt the config file format used by the `cloud-provider-openstack` or, even better, the `clouds.yaml` format (gophercloud has support for the latter already). Here's an example of what the yaml would look like:

```
clouds:
  my_cloud:
    insecure: true
    verify: false
    identity_api_version: 3
    auth:
      auth_url: http://10.0.0.14:5000/v3
      project_name: admin
      username: admin
      password: $SUPER_PASSWORD
      project_domain_name: Default
      user_domain_name: Default
    region: RegionOne
```

Thoughts?

/cc @Lion-Wei
