### ISSUE TITLE
Add Openstack compute labels to k8s nodes nodes

### ISSUE THREAD

**Issue by cunningr** [kubernetes-sigs/cluster-api-provider-openstack#1605]
/kind feature

**Describe the solution you'd like**

When creating k8s worker nodes we would like to see a node label indicating (or representing) the underlying physical compute node so that apps can be deployed using [topology spread constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) and avoid scheduling to the same physical node.

In a topology where we host multiple k8s worker instances on the same physical compute this is an important requirement for some applications.

**Anything else you would like to add:**
.

**Comment by nikParasyr** [comment]
wouldn't this work for your case => https://cluster-api.sigs.k8s.io/developer/architecture/controllers/metadata-propagation.html#machine

**Comment by cunningr** [comment]
Thank you.  Possibly, although I am missing how the label gets onto the machine.  I am aware that we are running quite an old version so maybe this has already been solved, but when I check the available labels on the machine, I only see:

```
  labels:
    cluster.x-k8s.io/cluster-name: clusterABC123
    machine-template-hash: "916525549"
    custom.label1/cluster: clusterABC123
    custom.label2/component: worker
    custom.label3/node-group: md-0
```

In the OSM has the same labels as above.  Do more recent versions of CAPO add labels for the instance compute host?

**Comment by nikParasyr** [comment]
The above is a capi feature introduced on capi 1.4.0 (IIRC). Basically it allows you to propagate labels/annotations. The same page explains how it works and which labels/annotations are propagated from which resources to which.

For example from [here](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/metadata-propagation.html#machinedeployment) we are adding labels to `.spec.template.metadata.labels` which get propagated to the node.

In our case we use that to set the role of nodes
 
Code:
```
spec:
...
  template:
    metadata:
      labels:
        node-role.kubernetes.io/worker: worker
```

and then the nodes in the cluster:
```
❯ kubectl get node                                                                                                                                                                                                                        
NAME                                 STATUS   ROLES           AGE   VERSION
capi-dev-control-plane-5f8hr-64qf7   Ready    control-plane   8d    v1.26.4
capi-dev-control-plane-5f8hr-p25bj   Ready    control-plane   8d    v1.26.4
capi-dev-control-plane-5f8hr-xsnmb   Ready    control-plane   8d    v1.26.4
capi-dev-md-0-infra-nnh88-wtcw2      Ready    worker          8d    v1.26.4
capi-dev-md-0-infra-nnh88-wz48g      Ready    worker          8d    v1.26.4
capi-dev-md-0-infra-nnh88-z29qt      Ready    worker          8d    v1.26.4

```

These labels/annotations are updated in-place and you dont need to roll-out new machines
