### ISSUE TITLE
Runtime error with v1alpha6 conversion on v0.8.0-alpha.0

### ISSUE THREAD

**Issue by nikParasyr** [kubernetes-sigs/cluster-api-provider-openstack#1606]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- Upgrade to v0.8.0-alpha.0: `clusterctl upgrade apply -i capo-system/openstack:v0.8.0-alpha.0`
- Clusters are still using v1alpha6
- Check capo logs (below) 

<details>
  <summary>logs</summary>
  
  ```
2023/07/07 06:52:32 http: panic serving 10.99.241.64:22859: runtime error: invalid memory address or nil pointer dereference
goroutine 5876 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1850 +0xbf
panic({0x17f4fa0, 0x29f45c0})
        /usr/local/go/src/runtime/panic.go:890 +0x262
sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha6.(*OpenStackCluster).ConvertFrom(0xc0011be000, {0x1cc2c98?, 0xc0008b7c00})
        /workspace/api/v1alpha6/conversion.go:188 +0xad
sigs.k8s.io/controller-runtime/pkg/webhook/conversion.(*Webhook).convertObject(0xc0006c5dd0?, {0x1cb4920, 0xc0008b7c00}, {0x1cb47e0, 0xc0011be000})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/webhook/conversion/conversion.go:148 +0x479
sigs.k8s.io/controller-runtime/pkg/webhook/conversion.(*Webhook).handleConvertRequest(0xc0006c5dd0, 0xc00087cdc0)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/webhook/conversion/conversion.go:113 +0x24b
sigs.k8s.io/controller-runtime/pkg/webhook/conversion.(*Webhook).ServeHTTP(0x1cadf00?, {0x7f7cf11e17a0?, 0xc002888730}, 0xc000207200)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/webhook/conversion/conversion.go:80 +0x108
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1({0x7f7cf11e17a0, 0xc002888730}, 0x1cc2b00?)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:60 +0xd4
net/http.HandlerFunc.ServeHTTP(0x1cc2b78?, {0x7f7cf11e17a0?, 0xc002888730?}, 0x6d45e0?)
        /usr/local/go/src/net/http/server.go:2109 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x1cc2b78?, 0xc0000b28c0?}, 0xc000207200)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:146 +0xb8
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1cc2b78?, 0xc0000b28c0?}, 0xc00120d8f0?)
        /usr/local/go/src/net/http/server.go:2109 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2({0x1cc2b78, 0xc0000b28c0}, 0xc000207200)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:108 +0xbf
net/http.HandlerFunc.ServeHTTP(0xc0000b28c0?, {0x1cc2b78?, 0xc0000b28c0?}, 0x1a1e512?)
        /usr/local/go/src/net/http/server.go:2109 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00120d8ce?, {0x1cc2b78, 0xc0000b28c0}, 0xc000207200)
        /usr/local/go/src/net/http/server.go:2487 +0x149
net/http.serverHandler.ServeHTTP({0x1cb41c8?}, {0x1cc2b78, 0xc0000b28c0}, 0xc000207200)
        /usr/local/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc00247a320, {0x1cc43f8, 0xc0006b8900})
        /usr/local/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3102 +0x4db


  ```
</details>

**What did you expect to happen:**

**Anything else you would like to add:**
- after i upgraded all my clusters to use v1alpha7 the issue was gone
- based on the docs [here](https://cluster-api-openstack.sigs.k8s.io/topics/crd-changes/v1alpha6-to-v1alpha7.html#v1alpha6-compared-to-v1alpha7) it seems we dont need to update our specs for any cluster (on all our clusters we let capo create networks/ports/sgs so we dont seem to be affected by the changes as far as i could determine)

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): [v0.8.0-alpha.0](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/tag/v0.8.0-alpha.0)
- Cluster-API version: 1.4.1
- OpenStack version: Victoria

**Comment by jichenjc** [comment]
@mdbooth FYI, I think there are some edge case that 6-> 8 has problem 

@nikParasyr maybe you can share your spec as reference as well..

**Comment by nikParasyr** [comment]
```
spec:
  allowAllInClusterTraffic: false
  apiServerLoadBalancer:
    allowedCidrs:
    - ...
    - ...
    - ...
    enabled: true
  bastion:
    enabled: true
    instance:
      cloudName: ""
      flavor: generic-2core-4gb-50gb
      image: centos_8
      sshKeyName: satellite-dev-ssh
  cloudName: satellite-dev
  controlPlaneEndpoint:
    host: actualIP
    port: 6443
  disableAPIServerFloatingIP: false
  dnsNameservers:
  - dnsserver1
  - dnsserver2
  externalNetworkId: 3ad3fbfe-2953-4753-8bab-5bea7a32865f
  identityRef:
    kind: Secret
    name: satellite-dev-cloud-config
  managedSecurityGroups: true
  network: {}
  nodeCidr: 192.168.0.0/16
  subnet: {}
  tags:
  - managed-by::cluster-api
  - cluster-name::satellite-dev
```
