### ISSUE TITLE
Our control plane security groups are too open

### ISSUE THREAD

**Issue by EmilienM** [kubernetes-sigs/cluster-api-provider-openstack#1704]
/kind bug

**What steps did you take and what happened:**
* A lot of default rules are too opinionated (specific to CNI)
* `additionalPorts` allows to create more rules, but automatically allow TCP and UDP, which is too opinionated.

**What did you expect to happen:**

We should make the security group rules protocols explicit (ideally in v1beta1).

**Comment by jichenjc** [comment]
there are multiple issues talked about security group 
such as CNI https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1346

what's the proposed suggestion of this issue?

**Comment by jichenjc** [comment]
yes, I think there are proposal to split the Sec group creation from code and make them into some kind of yaml file
so you are able to choose predefined yaml file as sec group (rules) and able to customerize as well
but it's unfortunately not implemented yet

**Comment by mdbooth** [comment]
The code will be gratefully received though!

@dulek I like the idea of a cluster spec flag which would disable creation of the calico rules when using managed security groups. That would also give us a route to deprecating these hard-coded rules.

**Comment by wwentland** [comment]
I like the approach taken in the AWS provider for CNIs, who [define a variety of resources](https://cluster-api-aws.sigs.k8s.io/crd/index.html) to tailor cluster security groups to your needs. 

Specifically, the following look interesting:

- [CNISpec](https://cluster-api-aws.sigs.k8s.io/crd/index.html#infrastructure.cluster.x-k8s.io/v1beta1.CNISpec)
- [CNIIngressRules](https://cluster-api-aws.sigs.k8s.io/crd/index.html#infrastructure.cluster.x-k8s.io/v1beta1.CNIIngressRules)
- [CNIIngressRule](https://cluster-api-aws.sigs.k8s.io/crd/index.html#infrastructure.cluster.x-k8s.io/v1beta1.CNIIngressRule)

This looks like the following in practice:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  name: foo
spec:
  network:
    cni:
      cniIngressRules:
      - description: cilium-health
        fromPort: 4240
        protocol: tcp
        toPort: 4240
      - ...
``` 

They also utilise `IngressRules` in various places and work quite well in "bring your own infrastructure" cases where users have externally managed security groups.
