### ISSUE TITLE
Add option to customize resource prefixes

### ISSUE THREAD

**Issue by fdobrovolny** [kubernetes-sigs/cluster-api-provider-openstack#1719]
/kind feature

**Describe the solution you'd like**
I want to be able to specify in the `OpenStackCluster` resource prefixes for the following resources which are now constants:
* network - [`networkPrefix string = "k8s-clusterapi"` ](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/cc304b8af1d5f637419273b0702a0311b3c17b01/pkg/cloud/services/networking/service.go#L32)
* router - uses network prefix
* subnet - uses network prefix
* ApiServerLoadBalancer - [`networkPrefix   string = "k8s-clusterapi"`](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/cc304b8af1d5f637419273b0702a0311b3c17b01/pkg/cloud/services/loadbalancer/loadbalancer.go#L42C1-L45)
* SecurityGroup - [`secGroupPrefix     string = "k8s"`](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/networking/securitygroups.go#L30-L36)

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
kind: OpenStackCluster
metadata:
  name: <cluster-name>
  namespace: <cluster-namespace>
spec:
  ...
  network:
    prefix: myPrefix
  apiServerLoadBalancer:
    prefix: myPrefix
  securityGroups:
    prefix: myPrefix
```

**Anything else you would like to add:**
* I want this to improve operator visibility into resource association with individual clusters when multiple clusters run inside a single OpenStack project.
* This feature request is a result of the following issue, which may give a more complete context of our use case: https://github.com/SovereignCloudStack/k8s-cluster-api-provider/issues/495
