### ISSUE TITLE
Add option to tag Api Server floating IP

### ISSUE THREAD

**Issue by fdobrovolny** [kubernetes-sigs/cluster-api-provider-openstack#1720]
/kind feature

**Describe the solution you'd like**
I want to be able to specify custom tags and/or maybe some part of the description of the floating IP in the `OpenStackCluster` resource.
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
kind: OpenStackCluster
metadata:
  name: <cluster-name>
  namespace: <cluster-namespace>
spec:
  ...
  apiServerFloatingIPTags:
    - myCustomTag
  apiServerFloatingIPDescription: My own description.
```

**Anything else you would like to add:**
* Floating IP Creation:  https://github.com/kubernetes/cloud-provider-openstack/blob/f6ca48ee768260444db6762447f1cd071f52b6fd/pkg/openstack/loadbalancer.go#L978-L982
* I want this to improve operator visibility into resource association with individual clusters when multiple clusters run inside a single OpenStack project.
* This feature request is a result of the following issue, which may give a more complete context of our use case: https://github.com/SovereignCloudStack/k8s-cluster-api-provider/issues/495
