### ISSUE TITLE
Reconcile attempts forbidden OpenstackMachine spec patch

### ISSUE THREAD

**Issue by strudelPi** [kubernetes-sigs/cluster-api-provider-openstack#1787]
/kind bug

**What steps did you take and what happened:**
Starting from a working workload cluster with a machine with the following "okay" state:
`Machine` status: TLDR; `all True`
`OpenstackMachine`:
```
status:
  conditions:
  - lastTransitionTime: "2023-12-11T14:46:30Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-12-11T14:46:30Z"
    status: "True"
    type: InstanceReady
  instanceState: ACTIVE
  ready: true
```
Delete a VM (in horizon) underlying a workload cluster. 
___
## User view
- a new VM is created, the `OpenstackMachine`'s `status` is kept **exactly** the same (timestamps also) - which I interpreted as "okay, never changed to false"
- `Machine` status is not ok though:
```
status:
  conditions:
  - lastTransitionTime: "2023-12-11T14:56:27Z"
    reason: NodeNotFound
    severity: Error
    status: "False"
    type: NodeHealthy
```
- CAPO error logs:
```
controller.go:324] "Reconciler error" err="admission webhook \"validation.openstackmachine.infrastructure.cluster.x-k8s.io\" denied the request: OpenStackMachine.infrastructure.cluster.x-k8s.io \"test4-capi-md-0-hwp75\" is invalid: spec: Forbidden: cannot be modified" controller="openstackmachine" controllerGroup="infrastructure.cluster.x-k8s.io" ...
```
- can only be helped by deleting the `Machine`
## Observations
The webhook log is coming from [here](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/1efeaf76b071ba64386ceecab91c4308356fa8e8/api/v1alpha7/openstackmachine_webhook.go#L113) therefore `OpenstackMachine`'s `spec` (which is immutable by design) is being changed.

This happens during regular `OpenstackMachine` reconcile in [getOrCreate](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/1347c0064b8224303b7e06e2db8e7cb340ba3c3d/controllers/openstackmachine_controller.go#L331) func. Instance is fetched by name, is recreated because it doesn't exist and `instanceStatus` is returned and assigned to the `openstackMachine` var. This [defer](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/1347c0064b8224303b7e06e2db8e7cb340ba3c3d/controllers/openstackmachine_controller.go#L137) makes sure all changes to the object are patched to the `OpenstackMachine` CR. This then causes:
1. the webhook admission error, because a `spec.providerID` & `spec.instanceID` update is attempted
2. the `OpenstackMachine` is not up to date with what the actual state of Openstack is

**What did you expect to happen:**
- No errors on CAPO side.
- `OpenstackMachine` CR being up to date (instead there is `instanceID` of the old resource from Openstack present which seems very misleading) 

**Anything else you would like to add:**
- Originally discussed in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1741 making new issue based on [slack convo](https://kubernetes.slack.com/archives/CFKJB65G9/p1702302439713059?thread_ts=1702035038.998529&cid=CFKJB65G9).
- maybe this scenario should be handled the same as a other errors on Openstack side ("Not reconciling machine in failed state.")

**Environment:**

- Cluster API Provider OpenStack version: v0.8.0
- Cluster-API version: v1.5.3
- OpenStack version: yoga
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`): 1.27.3
- OS (e.g. from `/etc/os-release`): ubuntu-20.04
