### ISSUE TITLE
Add the ability to specify a configurable VIP network for loadbalancer

### ISSUE THREAD

**Issue by oblazek** [kubernetes-sigs/cluster-api-provider-openstack#1809]
/kind feature

**Describe the solution you'd like**

Based on an API documentation of [openstack/octavia](https://docs.openstack.org/api-ref/load-balancer/v2/index.html#create-a-load-balancer) it should be possible to specify a VIP network for the loadbalancer:

```
Provide a vip_port_id.
Provide a vip_network_id.
Provide a vip_subnet_id.
```
which is possible in the [openstack API](https://github.com/gophercloud/gophercloud/blob/master/openstack/loadbalancer/v2/loadbalancers/requests.go#L87-L101)

and used in CAPO [here](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/loadbalancer/loadbalancer.go#L176), but is strictly filled by [this](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/loadbalancer/loadbalancer.go#L81) -> `openStackCluster.Status.Network.Subnets[0].ID`.

Unfortunately this is expecting that loadbalancer is supposed to be created on the same network/subnet as the VM itself which is not always the correct assumption. In our case we have a separate network for the loadbalancer from which the VIP should be allocated and a separate network for the control plane and worker nodes (VMs). 
This is a setup with octavia and our own specific cloud provider, so there are no amphoras nor floating IPs (the openstack is using calico as network driver). 

So either `OpenStackCluster` and/or `OpenStackMachineTemplate` should have the possibility to specify which network/subnet ID should be used just for the VIP/loadbalancer separately from `OpenStackMachineSpec.network` or `OpenStackMachineSpec.subnet`. E.g. something like, but not strictly in this way:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
kind: OpenStackCluster
metadata:
  name: test2
  namespace: test2
spec:
  cloudName: ulab1-test-infra8
  controlPlaneAvailabilityZones:
  - az1
  - az2
  - az3
  identityRef:
    kind: Secret
    name: test2-cloud-config
  apiServerLoadBalancer:
    enabled: true
  disableAPIServerFloatingIP: true
+  loadBalancerNetwork:
+    name: labrador
  managedSecurityGroups: true
  network:
    name: ulab1
  subnet:
    name: ulab1-ipv4-1
```

**Anything else you would like to add:**
Partly similar issue is: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1558 and related thread https://kubernetes.slack.com/archives/CFKJB65G9/p1702562005631379

cc @mdbooth
