### ISSUE TITLE
OpenStackFloatingIPPool: IPAddress index should include check kind

### ISSUE THREAD

**Issue by bilbobrovall** [kubernetes-sigs/cluster-api-provider-openstack#1863]
/kind bug

**What steps did you take and what happened:**
Create an OpenStackFloatingIPPool named test 
Create an IPAddress with poolRef 
```
poolRef:
  apiGroup: infrastructure.cluster.x-k8s.io
  kind: DoesNotExist
  name: test
```

Pool adds the ip to status.ClaimedIPs and handles it like it was created by the pool

**What did you expect to happen:**
The pool to only care about IPs with `kind == OpenStackFloatingIPPool`
