### ISSUE TITLE
CI tests generate weird external network

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1931]
CI jobs are generating clusters with

```yaml
  spec:
    externalNetwork:
      id: null
```

This is valid, but weird. We could either omit it or specify it by name.

/kind bug
