### ISSUE TITLE
Cannot add SG rule with `remoteIPPrefix`

### ISSUE THREAD

**Issue by jnummelin** [kubernetes-sigs/cluster-api-provider-openstack#2075]
/kind bug

**What steps did you take and what happened:**
Adding SG rules for e.g. SSH fails:

```yaml
  managedSecurityGroups:
    allowAllInClusterTraffic: true
    allNodesSecurityGroupRules:
      - description: Allow SSH to cluster all nodes
        direction: ingress
        etherType: IPv4
        name: SSH
        portRangeMax: 22
        portRangeMin: 22
        protocol: tcp
        remoteIPPrefix: "0.0.0.0/0"
```

This fails to reconcile:
```
"failureMessage": "failed to reconcile security groups: remoteManagedGroups is required",
```

The [docs](https://cluster-api-openstack.sigs.k8s.io/api/v1beta1/api#infrastructure.cluster.x-k8s.io/v1beta1.SecurityGroupRuleSpec) say that I should be able to provide only the prefix, right:
```
You can specify either remoteGroupID or remoteIPPrefix or remoteManagedGroups
```

**What did you expect to happen:**
I was expecting to have a rule in the managed SG to allow SSH

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): `v0.10.2`
- Cluster-API version: 
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`): 1.29.4
- OS (e.g. from `/etc/os-release`):
