### ISSUE TITLE
User provided router is not reconciled

### ISSUE THREAD

**Issue by MaysaMacedo** [kubernetes-sigs/cluster-api-provider-openstack#2129]
/kind bug

**What steps did you take and what happened:**
When an existent router is provided in the openstack cluster spec, that is not reconciled [here](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/controllers/openstackcluster_controller.go#L727). The router is only reconciled when created by CAPO [here](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/controllers/openstackcluster_controller.go#L789).

**What did you expect to happen:**
The provided router would be reconciled and the ID of the router would be present on the status of the OpenStack cluster object.

**Comment by EmilienM** [comment]
Bleurk, this is a valid issue. Let me know if you need help on this one.

**Comment by huxcrux** [comment]
Isn't the point with a user provided router that it shouldn't be reconciled? The only thing that should be needed is a router interface in all subnets?

**Comment by mdbooth** [comment]
What's the impact of this? Can you describe a problem that this causes?

**Comment by MaysaMacedo** [comment]
@huxcrux @mdbooth I noticed the user provided [network and subnet](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/controllers/openstackcluster_controller.go#L727) IDs are set in the status, but the ID of the user provided router in not the status. The only place where this is really a problem seems to be [here](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/b55a841bd7dbccce52762befb06e20766189688d/pkg/cloud/services/loadbalancer/loadbalancer.go#L228). But, in general as a user I thought that all the resources would end up having the ID resolved in the status.

Here is the example:

```
  spec:
    controlPlaneEndpoint:
      host: x.x.x.x
      port: 6443
    externalNetwork:
      filter:
        name: test
    identityRef:
      cloudName: openstack
      name: openstack-credentials
    managedSecurityGroups:
      allowAllInClusterTraffic: false
    network:
      filter:
        tags:
        - test
    router:
      filter:
        tags:
        - test
    subnets:
    - filter:
        tags:
        - test
  status:
    controlPlaneSecurityGroup:
      id: 823b7ed4-76f3-4087-89c3-ab109cefda08
      name: k8s-cluster-clusters-openstack-openstack-secgroup-controlplane
    externalNetwork:
      id: 316eeb47-1498-46b4-b39e-00ddf73bd2a5
      name: provider_net_shared_3
    failureDomains:
      nova:
        controlPlane: true
    network:
      id: d57c6e63-4060-4f83-904d-1075da54aa18
      name: test
      subnets:
      - cidr: 10.200.0.0/24
        id: b58f80ad-e6b0-40d9-946a-23a4be3e8905
        name: test
        tags:
        - test
      tags:
      - test
    ready: true
    workerSecurityGroup:
      id: 389e230d-2cc4-4fc8-b542-b32dc8dd7264
      name: k8s-cluster-clusters-openstack-openstack-secgroup-worker
```
