### ISSUE TITLE
Restart Control Plane api load balancer stays in error

### ISSUE THREAD

**Issue by nilpntr** [kubernetes-sigs/cluster-api-provider-openstack#2176]
/kind bug

**What steps did you take and what happened:**
I've restarted a management cluster's control plane(have 1 in my test setup and 1 worker node) after the restart the octavia load balancer stays in Operating Status error. When I take look at the logs in my control plane, it's trying to access itself through the load balancer ip.

**What did you expect to happen:**
I expect that it should be able restart even though it's a single control plane cluster(testing purposes).

**Anything else you would like to add:**
I've tweaked the base clusterctl generate cluster output a bit.
```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: cicd-cluster-control-plane
  namespace: openstack-cicd
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          oidc-issuer-url: ***
          oidc-client-id: ***
          oidc-username-claim: email
          oidc-groups-claim: groups
          oidc-groups-prefix: '***:'
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    files: []
    initConfiguration:
      apiVersion: kubeadm.k8s.io/v1beta3
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackMachineTemplate
      name: cicd-cluster-control-plane
  replicas: 1
  version: v1.30.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: cicd-cluster
  namespace: openstack-cicd
spec:
  apiServerLoadBalancer:
    enabled: true
  disableAPIServerFloatingIP: true
  network:
    id: ***
  subnets:
    # ipv4
    - id: ***
    # ipv6
    - id: ***
  externalNetwork:
    id: ***
  identityRef:
    cloudName: openstack
    name: cicd-cluster-cloud-config
  managedSecurityGroups:
    allNodesSecurityGroupRules:
      - description: Created by cluster-api-provider-openstack - BGP (calico)
        direction: ingress
        etherType: IPv4
        name: BGP (Calico)
        portRangeMax: 179
        portRangeMin: 179
        protocol: tcp
        remoteManagedGroups:
          - controlplane
          - worker
      - description: Created by cluster-api-provider-openstack - IP-in-IP (calico)
        direction: ingress
        etherType: IPv4
        name: IP-in-IP (calico)
        protocol: "4"
        remoteManagedGroups:
          - controlplane
          - worker
      - description: Created by *** to allow tailscale
        direction: ingress
        etherType: IPv4
        name: Allow tailscale
        portRangeMin: 0
        portRangeMax: 0
        remoteIPPrefix: "100.0.0.0/8"
      - description: Created by *** to allow internal network in project
        direction: ingress
        etherType: IPv4
        name: Allow internal
        portRangeMin: 0
        portRangeMax: 0
        remoteIPPrefix: "172.16.1.0/24"
```

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): latest
- Cluster-API version: 0.10.5
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`): 1.30
- OS (e.g. from `/etc/os-release`): Ubuntu
