### ISSUE TITLE
Regression: identityRef field in OpenStackMachine is ignored by CAPO manager

### ISSUE THREAD

**Issue by MatthieuFin** [kubernetes-sigs/cluster-api-provider-openstack#2190]
/kind bug

**What steps did you take and what happened:**
I create a cluster kind and deploy CAPO from main branch:
```bash
clusterctl init
git clone git@github.com:kubernetes-sigs/cluster-api-provider-openstack.git
cd cluster-api-provider-openstack/
kustomize build config/default/ | kubectl apply -f -
```

I have 2 totally different OS cluster named `frsbg01` and `GRA11`
I have a secret with credentials to access to this 2 clusters:
```yaml
apiVersion: v1
stringData:
  clouds.yaml: |-
    clouds:
      frsbg01:
        auth:
          auth_url: "https://auth.frsbg01..."
          application_credential_id: "xxx"
          application_credential_secret: "xxx"
        region_name: "frsbg01"
        interface: "public"
        identity_api_version: 3
        auth_type: "v3applicationcredential"
      gra11:
        auth:
          auth_url: "https://auth.cloud...."
          application_credential_id: "xxx"
          application_credential_secret: "..."
        region_name: "GRA11"
        interface: "public"
        identity_api_version: 3
        auth_type: "v3applicationcredential"
kind: Secret
metadata:
  name: capoc-clouds-config
  namespace: capi-capoc
type: Opaque
```
I create an OpenstackCluster with identityRef to`frsbg01` cluster 
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: capoc
  namespace: capi-capoc
spec:
  apiServerLoadBalancer:
    enabled: true
  disableAPIServerFloatingIP: true
  network:
    filter:
      name: ntwk
  disableExternalNetwork: true
  identityRef:
    cloudName: frsbg01
    name: capoc-clouds-config
```
I create a cluster `capoc` with control-plane in `frsbg01` which work well.

Then I create a MachineDeployment to add an OpenStackMachineTemplate with identityRef to OS cloud `GRA11` to `capoc` cluster:
```yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: node-gra11
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: "openstack:///{{ instance_id }}"
          name: "{{ local_hostname }}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: capoc-pool1-d2-2-gra11
spec:
  template:
    spec:
      # d2-2 exist only on GRA11 cloud but error is:
      #  create OpenStack instance: error getting flavor from flavor name d2-2: Unable to find flavor with name d2-2
      #  which is less verbose
      #flavor: d2-2
      # use existing flavor on frsbg01 OS cluster to trigger more verbose error
      flavor: adv5-c4m19456
      image:
        filter:
          name: ubuntu-...
      rootVolume:
        sizeGiB: 300
        type: high-speed-gen2
        availabilityZone:
          name: nova
      identityRef:
        name: capoc-clouds-config
        cloudName: gra11
      ports:
      - network:
          filter:
            name: ntwk
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: capoc-pool1-d2-2-gra11
spec:
  replicas: 1
  clusterName: capoc
  template:
    metadata:
      annotations:
        cluster.x-k8s.io/openstack.cloud: GRA11
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: node-gra11
      clusterName: capoc
      failureDomain: nova
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        name: capoc-pool1-d2-2-gra11
      version: v1.28.9
```

**What did you expect to happen:**
I expect that CAPO call OS endpoint defined in `GRA11` configuration file refered by identityRef of `OpenStackMachineTemplate` `capoc-pool1-d2-2-gra11` to create my worker nodes. This is the behavior I observe in release v0.10.x and behavior explained in [documentation](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/docs/book/src/api/v1beta1/api.md#infrastructure.cluster.x-k8s.io/v1beta1.OpenStackMachineSpec) this field should override one defined in cluster object but it's not.

I can observe this error in CAPO logs when it try to create worker node VM: 
![image](https://github.com/user-attachments/assets/6e3b6347-c7cf-4547-89c8-7bfd46db7e81)
I declare a flavor existing on frsbg01 in definition of GRA11 node to trigger error on volume `high-speed-gen2` which don't existe on `frsbg01` because it show the endpoint url and proof that OS client talk to identityRef defined in cluster object instead of OpenStackMachine.

![image](https://github.com/user-attachments/assets/985a598f-7a3e-4c45-b7ba-bc3a6dca8993)

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): 852272197ad100fecd9cc7e95a77e88897812520
- Cluster-API version: v1.8.4
- Kubernetes version (use `kubectl version`): v1.28.9
