### ISSUE TITLE
Upgrading v0.9.0 -> v0.10.4, conversion of `v1alpha7` to `v1beta1` drops `.Spec` fields

### ISSUE THREAD

**Issue by cunningr** [kubernetes-sigs/cluster-api-provider-openstack#2204]
/kind bug

**What steps did you take and what happened:**

When upgrading fro v0.9.0 to v0.10.4 (`v1alpha6` -> `v1beta1`) we loose fields in the `OpenstackMachineTemplate`:

```
        vnicType: direct-physical
        disablePortSecurity: true
```

**What did you expect to happen:**

Sometime after the upgrade our `v1alpha7` (from source `v1alpha6`) are automatically upgraded to `v1beta1`.  The annotation `[cluster.x-k8s.io/conversion-data](http://cluster.x-k8s.io/conversion-data)` contains:

```
spec:
  h: JkslDFu3I5c=
  d:
    cloudName: lab-meme
    flavor: c1e.4xlarge
    image: capi-ubuntu-XXXX
    sshKeyName: clusterapi_key
    ports:
      - network:
          id: 107b90c2-c318-4b05-a5f8-cd855cb289da
        description: XXXXXX - PCI-PT port creation
        fixedIPs:
          - subnet:
              id: 7ffd66d1-6722-4c4b-a77a-d0a5bbd82745
        vnicType: direct-physical
        disablePortSecurity: true
    configDrive: true
    serverGroupID: d1674730-3e27-4d0b-bf9d-eaaa679d88ef
    identityRef:
      kind: Secret
      name: cloud-config-lab-meme-abcd
```

But the new `.Spec` looks like:

```
spec:
  template:
    spec:
      configDrive: true
      flavor: c1e.4xlarge
      identityRef:
        cloudName: lab-meme
        name: cloud-config-lab-meme-abcd
      image:
        filter:
          name: capi-ubuntu-XXXX
      ports:
      - description: XXXXXX - PCI-PT port creation
        fixedIPs:
        - subnet:
            id: 7ffd66d1-6722-4c4b-a77a-d0a5bbd82745
        network:
          id: 107b90c2-c318-4b05-a5f8-cd855cb289da
      serverGroup:
        id: d1674730-3e27-4d0b-bf9d-eaaa679d88ef
      sshKeyName: clusterapi_key
```

which is missing the `vnicType: direct-physical` and `disablePortSecurity: true`.  This results in new machines with the wrong port type and a default security-group attached.

**Anything else you would like to add:**

[This issue](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/2136) may be relevant.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.9.0 -> v0.10.4
- Cluster-API version: v1.7.3
- OpenStack version: Ocata
- Minikube/KIND version: N/A
- Kubernetes version (use `kubectl version`): v1.24
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04
