### ISSUE TITLE
How to set cluster name in Openstack Cloud Controller Manager?

### ISSUE THREAD

**Issue by kralicky** [kubernetes-sigs/cluster-api-provider-openstack#2500]
I have been running into this issue: https://github.com/kubernetes/cloud-provider-openstack/issues/2241, and [this comment](https://github.com/kubernetes/cloud-provider-openstack/issues/2241#issuecomment-1618921550) on the issue mentions that the cluster name needs to be unique in order for LoadBalancer names to not collide. 

I am currently installing the OCCM via ClusterResourceSet, like this:
```yaml
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: openstack-ccm
  namespace: capi
spec:
  strategy: Reconcile
  clusterSelector:
    matchLabels:
      ccm: openstack
  resources:
    - name: openstack-ccm-manifests
      kind: ConfigMap
```
where the configmap contains all of the manifests [here](https://github.com/kubernetes/cloud-provider-openstack/tree/master/manifests/controller-manager).

The default manifests have the "kubernetes" cluster name:
```yaml
- name: CLUSTER_NAME
  value: kubernetes
```

How do I pass the actual cluster name to these manifests? There does not appear to be a mechanism like variable substitution or templating available in this context. Or, is there a better way to install the OCCM?

**Comment by lentzi90** [comment]
I think perhaps this issue belongs to [cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack) and not cluster-api-provider-openstack?
Anyway, if you want to set a custom cluster name through CAPI, that could be done using the ClusterConfiguration of the KubeadmControlPlane:
https://pkg.go.dev/sigs.k8s.io/cluster-api@v1.10.1/bootstrap/kubeadm/api/v1beta1#ClusterConfiguration
For OCCM I think you need to patch those manifests. I would do it by creating a kustomization that gathers the manifests you linked to and then provide a patch that changes the cluster name.

**Comment by mnaser** [comment]
I agree, this is not a CAPO issue.  We use the Helm charts that we template out and you can set the cluster name there too.

**Comment by djcenox** [comment]
Better to use CAAPH:

```
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: openstack-ccm
  namespace: <namespace>
spec:
  clusterSelector:
    matchLabels:
      clusterName: <cluster_name_in_capi>
  repoURL: https://kubernetes.github.io/cloud-provider-openstack
  chartName: openstack-cloud-controller-manager
  version: 2.30.0
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: false
  valuesTemplate: |
    cluster:
      name: <cluster_name>
    cloudConfig:
      global:
        auth-url: <redacted>
        username: <redacted>
        password: <redacted>
        tenant-name: <redacted>
        domain-name: <redacted>
        region: <redacted>
      networking:
      loadBalancer:
        floating-network-id: <someid>
    secret:
      enabled: true
      create: true
      name: cloud-config
    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"
```
