### ISSUE TITLE
Get error 'Resource not found' when creating instance from machine service.

### ISSUE THREAD

**Issue by morvencao** [kubernetes-sigs/cluster-api-provider-openstack#268]
### Issue description:

After I workaround issue of [`unknown authority CA` issue](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/264), I encounter another issue when creating openstack instances from machine service.

See logs of cluster-api-controller:
```
I0320 07:24:36.575242       1 controller.go:114] Running reconcile Machine for openstack-master-5ptq7
I0320 07:24:39.329965       1 controller.go:184] Reconciling machine object openstack-master-5ptq7 triggers idempotent create.
E0320 07:24:52.032660       1 actuator.go:319] Machine error openstack-master-5ptq7: error creating Openstack instance: Create new server err: Resource not found
W0320 07:24:52.032882       1 controller.go:186] unable to create machine openstack-master-5ptq7: error creating Openstack instance: Create new server err: Resource not found
```
Here is my `clouds.yaml` and `machines.yaml`

```
clouds:
  openstack:
    auth:
      auth_url: https://xxxxx.com:5000/v3
      username: "xxxxxxx"
      password: "xxxxxxxxx"
      project_id: cfc34894651f4035a09f623a926af2d9
      project_name: "xxxxx"
      domain_name: "xxx"
      user_domain_name: "xxx"
    region_name: "RegionOne"
    interface: "public"
    identity_api_version: 3
```

```
items:
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    generateName: openstack-master-
    labels:
      set: master
  spec:
    providerSpec:
      value:
        apiVersion: "openstackproviderconfig/v1alpha1"
        kind: "OpenstackProviderSpec"
        flavor: m1.large
        image: u16.04-2018-23-1
        sshUserName: ubuntu
        keyName: cluster-api-provider-openstack
        availabilityZone: nova
        networks:
        - uuid: b518e837-9c2a-4ea8-a9ef-a2bd4d5764de
        floatingIP: x.x.x.x
        securityGroups:
        - uuid: 08fd7463-bdc0-4f5e-922f-697332e35b0b
        - uuid: 0bd39afa-90f5-48fa-bc5b-d08f011e930f
        - uuid: 54a80908-9f42-4dbe-b0c1-623cd852ab4f
        - uuid: dd2abe1a-3c0e-4cdd-adec-e906a328f25a
        tags:
        - master
        userDataSecret:
          name: master-user-data
          namespace: openstack-provider-system
    versions:
      kubelet: 1.12.3
      controlPlane: 1.12.3
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    generateName: openstack-node-
    labels:
      set: node
  spec:
    providerSpec:
      value:
        apiVersion: "openstackproviderconfig/v1alpha1"
        kind: "OpenstackProviderSpec"
        flavor: m1.medium
        image: u16.04-2018-23-1
        sshUserName: ubuntu
        keyName: cluster-api-provider-openstack
        availabilityZone: nova
        networks:
        - uuid: b518e837-9c2a-4ea8-a9ef-a2bd4d5764de
        floatingIP: x.x.x.x
        securityGroups:
        - uuid: 08fd7463-bdc0-4f5e-922f-697332e35b0b
        - uuid: 0bd39afa-90f5-48fa-bc5b-d08f011e930f
        - uuid: 54a80908-9f42-4dbe-b0c1-623cd852ab4f
        - uuid: dd2abe1a-3c0e-4cdd-adec-e906a328f25a
        tags:
        - worker
        userDataSecret:
          name: worker-user-data
          namespace: openstack-provider-system
    versions:
      kubelet: 1.12.3
```

Appreciate it if anyone who can help me?

@gyliu513 @xunpan

**Comment by jichenjc** [comment]
@morvencao it's unlikely to know where's the root cause given the info you provided, it's likely because some resource can't be found on cloud (openstack) side, can you help to check whether you have any way to increase log level and try again?

**Comment by morvencao** [comment]
@jichenjc After reverted the code back to https://github.com/kubernetes-sigs/cluster-api-provider-openstack/commit/db7963362ba20928da06d8d89a2a6dfd19a348c7, I didn't encounter the issue again.

**Comment by jichenjc** [comment]
let me check this @morvencao

**Comment by jichenjc** [comment]
maybe you can provide clusters.yaml here? the issue seems related to cluster

**Comment by morvencao** [comment]
@jichenjc
```
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  name: test1
spec:
    clusterNetwork:
        services:
            cidrBlocks: ["10.96.0.0/12"]
        pods:
            cidrBlocks: ["192.168.0.0/16"]
        serviceDomain: "cluster.local"
    providerSpec:
      value:
        apiVersion: "openstackproviderconfig/v1alpha1"
        kind: "OpenstackProviderSpec"
```
