### ISSUE TITLE
Clarify Tagging UI

### ISSUE THREAD

**Issue by iamemilio** [kubernetes-sigs/cluster-api-provider-openstack#280]
The tagging system is confusing as it is. Proposed changes:

```yaml
Tags:
  Cluster:
      Tags:
          - a tag applied to all resources created by capo
  Server:
    Tags:
      - a tag applied to servers only
    Disable: false // Default:false; for systems that don't support nova 2.52
  Network:
    Tags:
      - a tag for networking resources only
```

@chrisgl, @flaper87: thoughts?

**Comment by iamemilio** [comment]
The tagging system is confusing as it is. Proposed changes:

Machines.yaml
```yaml
Tags:
  - a tag applied to that specific machine
```

Cluster.yaml
```yaml
Tags:
  - a tag applied to all resources created in the cluster
  enableServerTags: true | false
```
