### ISSUE TITLE
unkonwn field commands throws when use generate-yaml.sh to generate the configuration.

### ISSUE THREAD

**Issue by hchenxa** [kubernetes-sigs/cluster-api-provider-openstack#301]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```
root@hchen1:~/hchen/src/sigs.k8s.io/cluster-api-provider-openstack/cmd/clusterctl/examples/openstack# ./generate-yaml.sh  -f clouds.yaml openstack ubuntu
Error: json: unknown field "commands"
```

the error was from :
```
kustomize build /root/hchen/src/sigs.k8s.io/cluster-api-provider-openstack/cmd/clusterctl/examples/openstack/provider-component/clouds-secrets
```

and the file like below:
```
terctl/examples/openstack# cat  /root/hchen/src/sigs.k8s.io/cluster-api-provider-openstack/cmd/clusterctl/examples/openstack/provider-component/clouds-secrets/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: cloud-config
  commands:
    clouds.yaml: "cat configs/clouds.yaml"
  type: Opaque
- name: cloud-selector
  commands:
    OS_CLOUD: "cat configs/os_cloud.txt"
  type: Opaque

namespace: openstack-provider-system
```

**What did you expect to happen:**

the command should work fine.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

my kustomize version: 
```
terctl/examples/openstack# kustomize version
Version: {KustomizeVersion:2.0.3 GitCommit:a6f65144121d1955266b0cd836ce954c04122dc8 BuildDate:2019-03-05T20:37:42Z GoOs:linux GoArch:amd64}
```

**Environment:**

- Cluster-api version:  
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): 1.13
- OS (e.g. from `/etc/os-release`):
