### ISSUE TITLE
Support setting Fixed IP on router

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-openstack#362]
/kind feature

**Describe the solution you'd like**
In our deployment all outgoing packets of a Kubernetes cluster in OpenStack get the source IP of the OpenStack router. To make Firewall management easier, we have the requirement to set a fixed IP on the router. This makes it for example possible to recreate the cluster and keep the router IP. Another reason for this is that our IPAM is done centrally, so we get an IP assigned which we then have to use for the router of a specific Kubernetes cluster.

Currently, it's only supported to set the `externalNetworkId` for a cluster (which is set 
[when the router is created in the Gatewayinfo](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/pkg/cloud/openstack/clients/networkservice.go#L227)). Similarly, I would propose to add an additional property called `externalRouterIPs` which configures the fixed IPs of the router in specific subnets. The implementation could look like:

cluster.yaml
````yaml
spec:
    providerSpec:
      value:
        apiVersion: "openstackproviderconfig/v1alpha1"
        kind: "OpenstackProviderSpec"
        externalNetworkId: "49ab8e48-c542-410f-929c-ec9b1830f40c"
        externalRouterIPs:
          - fixedIP: 58.18.112.81
            subnet:
              filter:
                name: k8s-cluster-default-is2pd020
````

The fixed IPs would then be added to the `GatewayInfo` (after resolving the subnetParam):

````
opts.GatewayInfo.ExternalFixedIPs = append(opts.GatewayInfo.ExternalFixedIPs,routers.ExternalFixedIP{
    IPAdress: externalRouterIP.FixedIP,
    SubnetID: subnetID,
})
````

**Anything else you would like to add:**

I can open a PR to implement this feature, if that's a desirable feature.

EDIT: Changed `externalFixedIP` to `externalRouterIP`
