### ISSUE TITLE
Doc about sshKeyName in machines.yaml

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#461]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I can't ssh to my controller node and find that this is because the ssh is controlled by KubeadmConfig now, so why we should keep sshKeyname in machines.yaml ??

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: OpenStackMachine
metadata:
  name: ${CLUSTER_NAME}-controlplane-0
  namespace: ${CLUSTER_NAME}
spec:
  flavor: m1.medium
  image: <Image Name>
  sshKeyName: cluster-api-provider-openstack

KubeadmConfig
...
 users:
  - name: ubuntu
    sshAuthorizedKeys:
    - "$MACHINE_CONTROLLER_SSH_PUBLIC_FILE_CONTENT"
```
**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
@sbueringer it tooks me a while to find this as I only set in machines.yaml..

**Comment by sbueringer** [comment]
@jichenjc Sounds good to me. I still saw the property in CAPA. Maybe we're missing something.

@detiber What do you think do we still need the sshKeyName field when authorized keys are managed & overwritten by cloud-init (via the CABPK)?

**Comment by jichenjc** [comment]
conceptually CABPK should be in charge of cloud-init so I assume machines should not handle that now :), let's see whether CAPA has some different way ~

**Comment by detiber** [comment]
@sbueringer @jichenjc for CAPA, we still have the field because we are leveraging the EC2 managed keypair rather than injecting a user-defined ssh private key through the cloud-init config. I would expect that a similar use case might be applicable to OpenStack as well.

**Comment by sbueringer** [comment]
@jichenjc I think we should keep the field if it's possible to let OpenStack handle the authorized keys and the kubeadm bootstrapper doesn't overwrite them if they are not set in the KubeadmConfig. Also conceptually there could be other bootstrap provider which may not have support for authorized keys.

**Comment by sbueringer** [comment]
I tried these variants:
* sshKeyName (`""`) set & sshAuthorizedKeys (of ubuntu user) set > I was able to connect
* sshKeyName (`""`) unset & sshAuthorizedKeys (of ubuntu user) set > I was able to connect
* sshKeyName (`""`) & users (`[]`) unset > TODO I wasn't able to connect

* sshKeyName (`""`) unset & sshAuthorizedKeys (`""`) (of ubuntu user) unset > I wasn't able to connect

So looks like cloud-init overwrites the key from OpenStack only if the user is configured with an empty array of sshAuthorizedKeys, which seems to be correct.

**Comment by jichenjc** [comment]
Let me dig deeper, at least my env seems different... I guess it might be because my username is cloudusr instead of ubuntu, guess I need check the cloud-init configuration and code deeply

**Comment by jichenjc** [comment]
ok, I checked the code and 
we have something like following, this means the key will be used when using cloud-init


```
server, err := servers.Create(s.computeClient, keypairs.CreateOptsExt{
                CreateOptsBuilder: serverCreateOpts,
                KeyName:           openStackMachine.Spec.SSHKeyName,
        }).Extract()
```

does following means no user set in kubeadmConfig and no sshkey given? @sbueringer 
sshKeyName ("") & users ([]) unset > TODO I wasn't able to connect

**Comment by sbueringer** [comment]
I'm not sure how OpenStack sets the ssh key. Is ist via userdata/cloud-init?

It means the KubeadmConfig is configured like this:
````
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  name: cluster-api-testing-controlplane-2
  namespace: cluster-api-testing
spec:
...
  users:
  - name: ubuntu
    sshAuthorizedKeys: []
````
And the sshKeyName is not set in OpenStackMachine.
````
