### ISSUE TITLE
Doc:  update how to use official image or build image

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#463]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

@sbueringer sorry, I encountered following issue in VM start, seems no kubeadm installed at all, and I checked the kubeadmconfig file generated, seems no kubeadm /kubectl install
this belongs to CABPK or CAPO? should we update the generate file to add this? 

**What did you expect to happen:**
Sep  9 02:35:02 test-cluster-controlplane-0 cloud-init[1315]: /var/lib/cloud/instance/scripts/runcmd: 2: /var/lib/cloud/instance/scripts/runcmd: kubeadm: not found
Sep  9 02:35:02 test-cluster-controlplane-0 cloud-init[1315]: Cloud-init v. 19.1-1-gbaa47854-0ubuntu1~16.04.1 running 'modules:final' at Mon, 09 Sep 2019 02:35:01 +0000. Up 53.23 seconds.
Sep  9 02:35:02 test-cluster-controlplane-0 cloud-init[1315]: 2019-09-09 02:35:02,017 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/runcmd [127]
Sep  9 02:35:02 test-cluster-controlplane

my cloud-init script:
```
-   path: /tmp/kubeadm.yaml
    owner: root:root
    permissions: '0640'
    content: |
      ---
      ---
      apiServer:
        extraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
        extraVolumes:
        - hostPath: /etc/kubernetes/cloud.conf
          mountPath: /etc/kubernetes/cloud.conf
          name: cloud
          readOnly: true
      apiVersion: kubeadm.k8s.io/v1beta1
      certificatesDir: ""
      clusterName: test-cluster
      controlPlaneEndpoint: 9.20.205.29:6443
      controllerManager:
        extraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
        extraVolumes:
        - hostPath: /etc/kubernetes/cloud.conf
          mountPath: /etc/kubernetes/cloud.conf
          name: cloud
          readOnly: true
        - hostPath: /etc/certs/cacert
          mountPath: /etc/certs/cacert
          name: cacerts
          readOnly: true
      dns:
        type: ""
      etcd: {}
      imageRepository: k8s.gcr.io
      kind: ClusterConfiguration
      kubernetesVersion: 1.15.0
      networking:
        dnsDomain: cluster.local
        podSubnet: 192.168.0.0/16
        serviceSubnet: 10.96.0.0/12

      ---
      apiVersion: kubeadm.k8s.io/v1beta1
      kind: InitConfiguration
      localAPIEndpoint:
        advertiseAddress: '{{ ds.ec2_metadata.local_ipv4 }}'
        bindPort: 6443
      nodeRegistration:
        kubeletExtraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
        name: '{{ local_hostname }}'

runcmd:
  - 'kubeadm init --config /tmp/kubeadm.yaml'
ntp:
  servers:
users:
  - name: cloudusr
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGPRj84C8TWrvr8qS2ZL7gysKp56bXP5EjSgG2Bxh89p6S/V+6Ix8NnkybA5Sl21KISZjd9PPtBqen4L/pQRpqqdGWCWPnViNFkNMDYXnkAD1l12Ft57auBFbTv9Ru4iXQlIW80NwHnIlDTIemhOrciK3iXuJ70fheXK9gQCaRMm8cLL3XaMkCQOqJgkH6auOMSZhYMDas7ZoDt/dbBufwZ6bZetv1WBgDa9JHNxQeC0/y3ageUVye1kLCowAsNZVf/CxwJudOc9Tn6ja9oFbyJRuG193JNhPpA/G27xitd5+a+eMaoxFCgWNmfpQehGYSGtAACb/kBsqqxh8FJwyH

```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
