### ISSUE TITLE
should not occure error when reconcile floatingIP

### ISSUE THREAD

**Issue by stewart-yu** [kubernetes-sigs/cluster-api-provider-openstack#487]
/kind bug

**What steps did you take and what happened:**

Run in `single-node` models with `floating IP`, the code in 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/controllers/openstackmachine_controller.go#L227-L233
will return error when `reconcile`

error like that
```
 errorMessage: 'FloatingIP cannot be reconciled: error associating floatingIP:
      Bad request with: [POST http://10.104.50.192:8774/v2/3fa5499390e34c0ea9f2519d41dccd1c/servers/77bb8290-e990-409d-9a87-097d76a47b8c/action],
      error message: {"badRequest": {"message": "Unable to associate floating ip 1.2.3.4
      to fixed ip 1.2.3.5 for instance 77bb8290-e990-409d-9a87-097d76a47b8c.
      Error: Cannot associate floating IP 1.2.3.4 (ac5a333e-6300-47ed-9a0f-d33822f02639)
      with port a0328f4e-bd04-4ac3-8fde-f461fb75c7f1 using fixed IP 1.2.3.5,
      as that fixed IP already has a floating IP on external network 116a9f2b-e032-4f8c-8c6b-103011ada1c4.",
      "code": 400}}'
```

**What did you expect to happen:**

if check the floating IP associating to the target instance (marked wit FixedIP),  should not error when reconcile

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
master
- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
@stewart-yu Did I understand it correctly that your master server already has another floating ip?

**Comment by stewart-yu** [comment]
no,  just one floating ip.

**Comment by stewart-yu** [comment]
IMO, if we create the given floating IP or the given floating IP not binded to `instance`, should we call the logic
```
if err := computeService.AssociateFloatingIP(instance.ID, openStackMachine.Spec.FloatingIP); err != nil {
			return fmt.Errorf("error associating floatingIP: %v", err)
}
```
, otherwise, no need

**Comment by sbueringer** [comment]
I don't really get what's happening.

Usually:
* The floating ip is created if it does not exist before
* The floating ip is assocated with the master VM

What is happening in your case?

The floating ip is created and then the associate fails. Why does the associate fail?

**Comment by stewart-yu** [comment]
> The floating ip is created and then the associate fails. Why does the associate fail?

the first time associate  is ok, the second time failed

**Comment by sbueringer** [comment]
Ah so it's assocating the same ip twice in consecutive reconcile loops?

**Comment by jichenjc** [comment]
seems `that fixed IP already has a floating IP on external network` has the info
so maybe we either check whether already associated a floating ip or ignore the error might be ok?

**Comment by sbueringer** [comment]
But I think there's something else wrong here. I tried it locally with a single-node cluster. I can associate the same floating ip as often as I want I don't get an error. @stewart-yu Can you post your OpenStackMachine resource and the output of `openstack server list` ?

**Comment by stewart-yu** [comment]
@sbueringer
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: OpenStackMachine
metadata:
  name: cloud-cluster-controlplane-0
  namespace: cloud-cluster
spec:
  availabilityZone: nova
  cloudName: devstack
  cloudsSecret:
    name: cloud-config
    namespace: cloud-cluster
  flavor: m1.medium
  floatingIP: 1.2.3.4
  image: "CentOS 7.6"
  sshKeyName: cluster-api-provider-openstack
```
and there are some reason specify, i can not access to `openstack CMD`
 i will check this problem double. Thanks for your reply
/hold
