### ISSUE TITLE
machine instance creation fails when OpenStackCluster includes cluster name as a tag

### ISSUE THREAD

**Issue by petergardfjall** [kubernetes-sigs/cluster-api-provider-openstack#501]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Created a cluster with the cluster name as one of its tags:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: OpenStackCluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: ${CLUSTER_NAME}
spec:
  ...
  tags: ["${CLUSTER_NAME}"]
```

The cluster was created but the machine provisioning later failed with:
```
E0127 12:39:26.060244       1 openstackmachine_controller.go:333] controllers/OpenStackMachine/openstackmachine-controller/namespace=openstack-k1/openStackMachine=controlplane-0/infrastructure.cluster.x-k8s.io/v1alpha2/machine=controlplane-0/cluster=openstack-k1/openStackCluster=openstack-k1 "msg"="OpenStack instance cannot be created: error creating Openstack instance: tagging port for server err: Bad request with: [PUT https://kna1.citycloud.com:9696/v2.0/ports/1b5a65ac-fa4d-44d8-9c79-4a6b112b5783/tags], error message: {\"NeutronError\": {\"message\": \"Invalid input for operation: Duplicate items in the list: 'openstack-k1'.\", \"type\": \"InvalidInput\", \"detail\": \"\"}}" "error"="UpdateError"
```

**What did you expect to happen:**
The control plane machines to be properly provisioned.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The problem is in `instance.go`. `machineTags` need to be de-duplicated.

**Environment:**

- Cluster-api version: alphav2
- KIND version: v0.7.0
- Kubernetes version: (use `kubectl version`): 1.15.0
- OS (e.g. from `/etc/os-release`): Ubuntu
