### ISSUE TITLE
Unable to use an existing network and `managedAPIServerLoadBalancer: true`

### ISSUE THREAD

**Issue by gdetal** [kubernetes-sigs/cluster-api-provider-openstack#547]
/kind bug

**What steps did you take and what happened:**

I created a cluster using:
 - an existing OpenStack network/subnet
 - `managedAPIServerLoadBalancer` enabled

The manifest I use is:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: OpenStackCluster
metadata:
  name: openstack
  namespace: default
spec:
  apiServerLoadBalancerAdditionalPorts:
  - 22
  apiServerLoadBalancerFloatingIP: 192.168.50.180
  apiServerLoadBalancerPort: 6443
  cloudName: openstack
  cloudsSecret:
    name: openstack-cloud-config
    namespace: default
  disablePortSecurity: true
  disableServerTags: true
  dnsNameservers:
  - 192.168.50.254
  externalNetworkId: dd02a459-0e4a-444d-9610-355709acbf1a
  managedAPIServerLoadBalancer: true
  network:
    name: "private-net"
  subnet:
    name: "private-subnet"
  useOctavia: false
```

`192.168.50.180` is an existing _unassigned_ floating address. And `private-net/subnet` are existing Network/Subnet.

Then no load balancer are created and thus the control plane node cannot initialize.

**What did you expect to happen:**

That a load balancer is created and that the control plan is initialized.

**Anything else you would like to add:**

If I set nodeCIDR instead of specifying and existing network and subnet. The setup works properly and a load balancer is created.

It seems that https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/controllers/openstackcluster_controller.go#L251 is missing a similar instruction `reconcileLoadBalancer` as the `else` case.

Note that if I delete the Cluster object then the `capo-controller-manager` crashes with:

```
E0420 12:06:03.224464       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 396 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1524ee0, 0x2427830)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1524ee0, 0x2427830)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/services/loadbalancer.(*Service).DeleteLoadBalancerMember(0xc0006b2980, 0xc0005d21e0, 0x11, 0xc0004e2fc0, 0xc0004e2b40, 0xc0003a2500, 0x0, 0x0)
	/workspace/pkg/cloud/services/loadbalancer/loadbalancer.go:420 +0x1dd
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackMachineReconciler).reconcileDelete(0xc0003f6ba0, 0x191a680, 0xc000080080, 0x19292e0, 0xc000724330, 0xc000526230, 0xc0004e2fc0, 0xc0004e2b40, 0xc0006a7980, 0xc0003a2500, ...)
	/workspace/controllers/openstackmachine_controller.go:216 +0x759
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackMachineReconciler).Reconcile(0xc0003f6ba0, 0xc0005061f9, 0x7, 0xc00047e900, 0x1d, 0xc0004ddc00, 0x0, 0x0, 0x0)
	/workspace/controllers/openstackmachine_controller.go:146 +0x9e5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002220c0, 0x15780e0, 0xc0001c8620, 0xc000630500)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.1/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002220c0, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.1/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0002220c0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.1/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005e13b0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005e13b0, 0x3b9aca00, 0x0, 0x1, 0xc000602000)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0005e13b0, 0x3b9aca00, 0xc000602000)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.1/pkg/internal/controller/controller.go:193 +0x328
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13c7a3d]
```

**Environment:**

- Cluster-api version: 

```
$ clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.3", GitCommit:"ecff70af1b839c4086335234d88b1b8c00c3383c", GitTreeState:"clean", BuildDate:"2020-03-27T22:25:19Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Minikube/KIND version:

```
$ kind version
kind v0.7.0 go1.13.6 linux/amd64
```

- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
