### ISSUE TITLE
Who manages ssh key?

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#567]
/kind bug

**What steps did you take and what happened:**

After cluster was created successfully, I logged in to the machine with user capo.
But the key was not ssh key pair on OpenStack, I am confused at first.

**What did you expect to happen:**

Ssh key should be managed by OpenStack.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

`openStackMachine.Spec.SSHKeyName` is still valid. Just use it instead of capo.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
from current code looks like you should be able to use openStackMachine.Spec.SSHKeyName 
to ssh ,correct? 

in templates/cluster-template-without-lb.yaml
sshAuthorizedKeys:
      - "${OPENSTACK_SSH_AUTHORIZED_KEY}"


how about remove the section 

```
users:
    - name: capo
      sudo: "ALL=(ALL) NOPASSWD:ALL"
      sshAuthorizedKeys:
      - "${OPENSTACK_SSH_AUTHORIZED_KEY}"
```

in template and replace it with openstack key ?

so seems we have 2 ssh keys

**Comment by hidekazuna** [comment]
> from current code looks like you should be able to use openStackMachine.Spec.SSHKeyName
> to ssh ,correct?

Yes. But I do not want 2 ssh keys.

In template, remove the following.

```
users:
    - name: capo
      sudo: "ALL=(ALL) NOPASSWD:ALL"
      sshAuthorizedKeys:
      - "${OPENSTACK_SSH_AUTHORIZED_KEY}"
```
Instead of the above, add `sshKeyName`  in OpenStackMachineTemplate like the following.

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: OpenStackMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-control-plane
spec:
  template:
    spec:
      sshKeyName: ${OPENSTACK_SSH_KEY_NAME}
```
We need to introduce ${OPENSTACK_SSH_KEY_NAME}, but do not change the go code.
