### ISSUE TITLE
wrong settings in security group not reported correctly

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#582]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

we allow such settings
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: OpenStackMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-control-plane
spec:
  template:
    spec:
      securityGroups:
      - name: allow-ssh
```

however, we don't report if `allow-ssh` not exist

if `allow_ssh` not exist, we should report this kind of error 
```
1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="error creating Openstack instance: security group allow_ssh not found"  "controller"="openstackmachine" "request"={"Namespace":"default","Name":"capi-quickstart-control-plane-fz8pc"
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
