### ISSUE TITLE
Does CAPI Openstack support bypassing Octavia LB 

### ISSUE THREAD

**Issue by eratnch** [kubernetes-sigs/cluster-api-provider-openstack#584]
Hi,
Is it possible to not use Octavia as the load balancing solution for CAPI openstack? In the cluster-template.yaml the following section mentions the load balancer ip, network and port details.

`apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: OpenStackCluster
metadata:
  name: tgtcluster
  namespace: default
spec:
  apiServerLoadBalancerAdditionalPorts:
  - 22
  apiServerLoadBalancerFloatingIP: 172.24.4.119
  apiServerLoadBalancerPort: 6443
  cloudName: devstack
  cloudsSecret:
    name: tgtcluster-cloud-config
    namespace: default
  disablePortSecurity: false
  disableServerTags: true
  dnsNameservers:
  - 8.8.8.8
  externalNetworkId: f6836c66-7bfc-4c22-a380-4a62b89b8b7f
  managedAPIServerLoadBalancer: true
  nodeCidr: 10.6.0.0/24
  useOctavia: true
`

However there might be scenarios where the users who have access to an external load balancer might not want to use Octavia or any other openstack specific LB service. In those scenarios, is it possible to bypass Octavia and use any other load balancer? If yes, then how does the manifest need to be modified? Please confirm.

**Comment by jichenjc** [comment]
yes, it allows, I actually created a env without LB last week

**Comment by jichenjc** [comment]
some FYI
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: OpenStackCluster
metadata:
  name: capi-quickstart
  namespace: default
spec:
  controlPlaneEndpoint:
    host: 172.24.4.2
    port: 6443
  cloudName: openstack
  cloudsSecret:
    name: capi-quickstart-cloud-config
    namespace: default
  disablePortSecurity: false
  disableServerTags: true
  dnsNameservers:
  - 9.20.136.11
  externalNetworkId: 3a916660-0559-4624-8854-9f2504b314cb
  managedAPIServerLoadBalancer: false
  managedSecurityGroups: true
  nodeCidr: 10.6.0.0/24
  useOctavia: false

```


```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: OpenStackMachineTemplate
metadata:
  name: capi-quickstart-control-plane
  namespace: default
spec:
  template:
    spec:
      floatingIP: 172.24.4.2
      cloudName: openstack
      cloudsSecret:
        name: capi-quickstart-cloud-config
        namespace: default
      flavor: m1.medium
      image: ubuntu2004
      securityGroups:
      - name: allow_ssh

```
