### ISSUE TITLE
Is clusterctl move supported for capo

### ISSUE THREAD

**Issue by eratnch** [kubernetes-sigs/cluster-api-provider-openstack#667]
Hi @jichenjc  @hidekazuna ,

Is `clusterctl move` command supported for capo?
If so, could you please point me to the documentation/steps that need to be done to do the move?

When I tried last time, it failed at the `clusterctl init` stage for the target cluster where `cert-manager` didn't get initialized. This is the previous step before the `clusterctl move` can be run.
Does it work for you?

**Comment by jichenjc** [comment]
@eratnch check this 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/docs/mover.md

**Comment by eratnch** [comment]
@jichenjc thanks for the link.
Which template file you used in the `clusterctl config` command to generate target cluster manifest?
I was using the `cluster-template.yaml` file with capo 0.3.1 release and faced the cert-manager problem.

**Comment by jichenjc** [comment]
it's not related to LB I guess ..
I am using cluster-template-external.yaml 
I am little bit confused , whch issue you are having ? init or move ? seems the issues's title is about move while you also talked about init ... please help to confirm, thanks

**Comment by eratnch** [comment]
Hi @jichenjc , so the move workflow is like below:
- create kind ephemeral cluster
- deploy control plane machines in target cluster (using external cloud e.g. devstack)
- deploy worker machines in target cluster
- initialize target cluster with capi core components (this is through cluster init --kubeconfig target-cluster-kubeconfig)
- cluster move

I get error in the initialize target cluster step. Cert-manager is never initialized.

How did you get it working? Did you need to do any special steps or configuration? I m using Octavia LB for devstack.

Another thing i noticed that `cluster-template-external.yaml` doesn't have any `OPENSTACK_CONTROLPLANE_IP` reference. So do we need to export it or it's not required any more?

Can you please advise?

**Comment by jichenjc** [comment]
@eratnch what I did is: 

1) kind create cluster;clusterctl init --infrastructure=openstack
this will create kind cluster and init the control pane on `temp` cluster
2) kubectl apply -f capi-quickstart.yaml.external
this will create VMs from openstack and create a workload cluster
3) now the machineset and capi resource is inside temp cluster and there is no capi resource in target workload cluster
4) init the workload cluster by using new kubeconfig 
5) move from temp to target workload cluster

so seems exactly same to your description above

so I will deploy a new one and paste all my stuffs here later on to for your reference

**Comment by jichenjc** [comment]
```
# kind create cluster;clusterctl init --infrastructure=openstack:v0.3.1
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.2) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a nice day! 👋
Fetching providers
Installing cert-manager
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v0.3.10" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v0.3.10" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v0.3.10" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-openstack" Version="v0.3.1" TargetNamespace="capo-system"

Your management cluster has been initialized successfully!

You can now create your first workload cluster by running the following:

  clusterctl config cluster [name] --kubernetes-version [version] | kubectl apply -f -
```

```
# kubectl apply -f capi-quickstart.yaml.external
cluster.cluster.x-k8s.io/capi-openstack-3 created
openstackcluster.infrastructure.cluster.x-k8s.io/capi-openstack-3 created
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/capi-openstack-control-plane created
openstackmachinetemplate.infrastructure.cluster.x-k8s.io/capi-openstack-control-plane created
machinedeployment.cluster.x-k8s.io/capi-openstack-md-0 created
openstackmachinetemplate.infrastructure.cluster.x-k8s.io/capi-openstack-md-0 created
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/capi-openstack-md-0 created
secret/capi-openstack-cloud-config created
```

I have VMs now 
```
# nova list
+--------------------------------------+------------------------------------+--------+------------+-------------+------------------------------------------------------------------------+
| ID                                   | Name                               | Status | Task State | Power State | Networks                                                               |
+--------------------------------------+------------------------------------+--------+------------+-------------+------------------------------------------------------------------------+
| 62937f99-2818-42d1-bb1d-2dbe892905ea | capi-openstack-control-plane-m2rwm | ACTIVE | -          | Running     | k8s-clusterapi-cluster-default-capi-openstack-3=10.6.0.193, 172.24.4.2 |
| a02d3f20-20b6-42ec-a168-5a049bebc65a | capi-openstack-md-0-fj22b          | ACTIVE | -          | Running     | k8s-clusterapi-cluster-default-capi-openstack-3=10.6.0.34              |
+--------------------------------------+------------------------------------+--------+------------+-------------+------------------------------------------------------------------------+
```

create kubeconfig
```
kubectl --namespace=default get secret/capi-openstack-3-kubeconfig -o jsonpath={.data.value}  | base64 --decode  > capi-openstack-3.kubeconfig
```

get pods 
```
# kubectl --kubeconfig capi-openstack-3.kubeconfig get pods --all-namespaces                                     NAMESPACE     NAME                                                         READY   STATUS    RESTARTS   AGE
kube-system   coredns-6955765f44-2rvvn                                     0/1     Pending   0          37m
kube-system   coredns-6955765f44-bhqd2                                     0/1     Pending   0          37m
kube-system   etcd-capi-openstack-control-plane-m2rwm                      1/1     Running   0          38m
kube-system   kube-apiserver-capi-openstack-control-plane-m2rwm            1/1     Running   0          38m
kube-system   kube-controller-manager-capi-openstack-control-plane-m2rwm   1/1     Running   0          38m
kube-system   kube-proxy-hvfhv                                             1/1     Running   0          37m
kube-system   kube-proxy-xhc5d                                             1/1     Running   0          34m
kube-system   kube-scheduler-capi-openstack-control-plane-m2rwm            1/1     Running   0          38m

```

do configuration 
```
curl https://docs.projectcalico.org/v3.12/manifests/calico.yaml | sed "s/veth_mtu:.*/veth_mtu: \"1430\"/g" | kubectl --kubeconfig capi-openstack-3.kubeconfig apply -f -

kubectl --kubeconfig capi-openstack-3.kubeconfig create secret -n kube-system generic cloud-config --from-file=/tmp/cloud.conf

```

now apply all external cloud provider CRDs

```
kubectl --kubeconfig capi-openstack-3.kubeconfig apply -f https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/cluster/addons/rbac/cloud-controller-manager-roles.yaml

kubectl --kubeconfig capi-openstack-3.kubeconfig apply -f https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/cluster/addons/rbac/cloud-controller-manager-role-bindings.yaml

kubectl --kubeconfig capi-openstack-3.kubeconfig apply -f https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
```


I got 
```
# kubectl --kubeconfig capi-openstack-3.kubeconfig get pods --all-namespaces
NAMESPACE     NAME                                                         READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-59b699859f-ps5tg                     1/1     Running   0          5m36s
kube-system   calico-node-4sprl                                            1/1     Running   0          5m36s
kube-system   calico-node-pkt47                                            1/1     Running   0          5m36s
kube-system   coredns-6955765f44-2rvvn                                     1/1     Running   0          47m
kube-system   coredns-6955765f44-bhqd2                                     1/1     Running   0          47m
kube-system   etcd-capi-openstack-control-plane-m2rwm                      1/1     Running   0          47m
kube-system   kube-apiserver-capi-openstack-control-plane-m2rwm            1/1     Running   0          47m
kube-system   kube-controller-manager-capi-openstack-control-plane-m2rwm   1/1     Running   0          47m
kube-system   kube-proxy-hvfhv                                             1/1     Running   0          47m
kube-system   kube-proxy-xhc5d                                             1/1     Running   0          44m
kube-system   kube-scheduler-capi-openstack-control-plane-m2rwm            1/1     Running   0          47m
kube-system   openstack-cloud-controller-manager-247zz                     1/1     Running   0          3m3s

```


then init on the target cluster
```
# clusterctl init --kubeconfig capi-openstack-3.kubeconfig --infrastructure=openstack:v0.3.1
Fetching providers
Installing cert-manager
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v0.3.10" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v0.3.10" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v0.3.10" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-openstack" Version="v0.3.1" TargetNamespace="capo-system"

Your management cluster has been initialized successfully!

You can now create your first workload cluster by running the following:

  clusterctl config cluster [name] --kubernetes-version [version] | kubectl apply -f -

-bash: $LOGFILE: ambiguous redirect
```

move the cluster
```
# clusterctl move --to-kubeconfig capi-openstack-3.kubeconfig -v 10
No default config file available
Performing move...
Discovering Cluster API objects
Cluster Count=1
KubeadmConfig Count=2
KubeadmConfigTemplate Count=1
KubeadmControlPlane Count=1
MachineDeployment Count=1
Machine Count=2
MachineSet Count=1
OpenStackCluster Count=1
OpenStackMachine Count=2
OpenStackMachineTemplate Count=2
Secret Count=9
Total objects Count=23
Moving Cluster API objects Clusters=1
Pausing the source cluster
Set Cluster.Spec.Paused Paused=true Cluster="capi-openstack-3" Namespace="default"
Creating target namespaces, if missing
Creating objects in the target cluster
Creating Cluster="capi-openstack-3" Namespace="default"
Creating KubeadmConfigTemplate="capi-openstack-md-0" Namespace="default"
Creating MachineDeployment="capi-openstack-md-0" Namespace="default"
Creating OpenStackMachineTemplate="capi-openstack-md-0" Namespace="default"
Creating KubeadmControlPlane="capi-openstack-control-plane" Namespace="default"
Creating OpenStackCluster="capi-openstack-3" Namespace="default"
Creating OpenStackMachineTemplate="capi-openstack-control-plane" Namespace="default"
Creating Secret="capi-openstack-3-kubeconfig" Namespace="default"
Creating Machine="capi-openstack-control-plane-fk6fr" Namespace="default"
Creating Secret="capi-openstack-3-etcd" Namespace="default"
Creating MachineSet="capi-openstack-md-0-775f546bc" Namespace="default"
Creating Secret="capi-openstack-3-ca" Namespace="default"
Creating Secret="capi-openstack-3-proxy" Namespace="default"
Creating Secret="capi-openstack-3-sa" Namespace="default"
Creating KubeadmConfig="capi-openstack-control-plane-8kj8v" Namespace="default"
Creating Machine="capi-openstack-md-0-775f546bc-5n766" Namespace="default"
Creating OpenStackMachine="capi-openstack-control-plane-m2rwm" Namespace="default"
Creating KubeadmConfig="capi-openstack-md-0-6jpc5" Namespace="default"
Creating Secret="capi-openstack-control-plane-8kj8v" Namespace="default"
Creating OpenStackMachine="capi-openstack-md-0-fj22b" Namespace="default"
Creating Secret="capi-openstack-md-0-6jpc5" Namespace="default"
Deleting objects from the source cluster
Deleting Secret="capi-openstack-md-0-6jpc5" Namespace="default"
Deleting KubeadmConfig="capi-openstack-md-0-6jpc5" Namespace="default"
Deleting Secret="capi-openstack-control-plane-8kj8v" Namespace="default"
Deleting OpenStackMachine="capi-openstack-md-0-fj22b" Namespace="default"
Deleting KubeadmConfig="capi-openstack-control-plane-8kj8v" Namespace="default"
Deleting Machine="capi-openstack-md-0-775f546bc-5n766" Namespace="default"
Deleting OpenStackMachine="capi-openstack-control-plane-m2rwm" Namespace="default"
Deleting Secret="capi-openstack-3-kubeconfig" Namespace="default"
Deleting Machine="capi-openstack-control-plane-fk6fr" Namespace="default"
Deleting Secret="capi-openstack-3-etcd" Namespace="default"
Deleting MachineSet="capi-openstack-md-0-775f546bc" Namespace="default"
Deleting Secret="capi-openstack-3-ca" Namespace="default"
Deleting Secret="capi-openstack-3-proxy" Namespace="default"
Deleting Secret="capi-openstack-3-sa" Namespace="default"
Deleting KubeadmConfigTemplate="capi-openstack-md-0" Namespace="default"
Deleting MachineDeployment="capi-openstack-md-0" Namespace="default"
Deleting OpenStackMachineTemplate="capi-openstack-md-0" Namespace="default"
Deleting KubeadmControlPlane="capi-openstack-control-plane" Namespace="default"
Deleting OpenStackCluster="capi-openstack-3" Namespace="default"
Deleting OpenStackMachineTemplate="capi-openstack-control-plane" Namespace="default"
Deleting Cluster="capi-openstack-3" Namespace="default"
Resuming the target cluster

```


make sure the machines got moved
```
# kubectl get machinedeployments --kubeconfig capi-openstack-3.kubeconfig --all-namespaces
NAMESPACE   NAME                  PHASE     REPLICAS   READY   UPDATED   UNAVAILABLE
default     capi-openstack-md-0   Running   1          1       1

```

**Comment by jichenjc** [comment]
please note I am still on 0.3.1 version (so some variables might be different) but mostly it should works..

```
# cat cloud.conf
[Global]
auth-url=http://10.43.0.134/identity
username="admin"
password="xxxxx"
tenant-id="8ffed29f121248ecae5f9fdddd3f16d6"
tenant-name="admin"
domain-name="default"
region="RegionOne"
-bash: $LOGFILE: ambiguous redirect

```



```
# cat capi-quickstart.yaml.external
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: capi-openstack-3
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: capi-openstack-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: OpenStackCluster
    name: capi-openstack-3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: OpenStackCluster
metadata:
  name: capi-openstack-3
  namespace: default
spec:
  controlPlaneEndpoint:
    host: 172.24.4.2
    port: 6443
  cloudName: openstack
  cloudsSecret:
    name: capi-openstack-cloud-config
    namespace: default
  disablePortSecurity: false
  dnsNameservers:
  - xxxxxxx
  externalNetworkId: 9865eeff-0f66-4b86-bcbb-847d9f4436ce
  managedAPIServerLoadBalancer: false
  managedSecurityGroups: true
  nodeCidr: 10.6.0.0/24
  useOctavia: false
---
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
metadata:
  name: capi-openstack-control-plane
spec:
  replicas: 1
  infrastructureTemplate:
    kind: OpenStackMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    name: capi-openstack-control-plane
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        name: '{{ local_hostname }}'
        kubeletExtraArgs:
          cloud-provider: external
    clusterConfiguration:
      controlPlaneEndpoint: 172.24.4.2:6443
      imageRepository: k8s.gcr.io
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    joinConfiguration:
      nodeRegistration:
        name: '{{ local_hostname }}'
        kubeletExtraArgs:
          cloud-provider: external
    ntp:
      servers: []
    users:
    - name: capo
      sshAuthorizedKeys:
      - <rsa>
      sudo: ALL=(ALL) NOPASSWD:ALL
  version: v1.17.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: OpenStackMachineTemplate
metadata:
  name: capi-openstack-control-plane
  namespace: default
spec:
  template:
    spec:
      floatingIP: 172.24.4.2
      cloudName: openstack
      cloudsSecret:
        name: capi-openstack-cloud-config
        namespace: default
      flavor: m1.medium
      image: ubuntu1910
      #securityGroups:
      #- name: allow_ssh
      #sshKeyName: jj
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: capi-openstack-md-0
  namespace: default
spec:
  clusterName: capi-openstack-3
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: capi-openstack-md-0
      clusterName: capi-openstack-3
      failureDomain: nova
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: OpenStackMachineTemplate
        name: capi-openstack-md-0
      version: v1.17.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: OpenStackMachineTemplate
metadata:
  name: capi-openstack-md-0
  namespace: default
spec:
  template:
    spec:
      cloudName: openstack
      cloudsSecret:
        name: capi-openstack-cloud-config
        namespace: default
      flavor: m1.medium
      image: ubuntu1910
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: capi-openstack-md-0
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: '{{ local_hostname }}'
          kubeletExtraArgs:
            cloud-provider: external
      ntp:
        servers: []
      users:
      - name: capo
        sshAuthorizedKeys:
        - "ssh-rsa xxxx'
        sudo: ALL=(ALL) NOPASSWD:ALL
---
apiVersion: v1
data:
  cacert: Cg==
  clouds.yaml: <secret>
kind: Secret
metadata:
  name: capi-openstack-cloud-config
  namespace: default
```

**Comment by jichenjc** [comment]
I will upgrade to v0.3.2 once the image is ready

**Comment by eratnch** [comment]
Thanks a lot @jichenjc , this certainly helps.
I'll try out once again to see if I get error at the same place.

**Comment by eratnch** [comment]
Wanted to add that I am using capo v0.3.1 and my yaml looks a little different from yours. Can you please take a look at the following?

```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: OpenStackCluster
metadata:
  name: target-cluster
  namespace: default
spec:
  apiServerLoadBalancerFloatingIP: ${OPENSTACK_CONTROLPLANE_IP}
  apiServerLoadBalancerPort: 6443
  cloudName: devstack
  cloudsSecret:
    name: target-cluster-cloud-config
    namespace: default
  disablePortSecurity: false
  disableServerTags: true
  dnsNameservers:
  - "${OPENSTACK_DNS_NAMESERVERS}"
  externalNetworkId: "{OPENSTACK_EXTERNAL_NETWORK_ID}"
  managedAPIServerLoadBalancer: true
  managedSecurityGroups: true
  nodeCidr: 10.6.0.0/24
  useOctavia: true
---
```
I am using octavia LB so set those parameters to true. Do I need to change any parameter?
