### ISSUE TITLE
image should be optional in openstackmachinespec 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#763]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```
externalNetworkId: 2571375f-206a-46b2-9905-6744a27bfc60
  managedAPIServerLoadBalancer: false
  managedSecurityGroups: true
  nodeCidr: 10.6.0.0/24
  useOctavia: false
  bastion:
    enabled: true
    failureDomain: nova
    instance:
      flavor: m1.tiny
      image: cirros-0.5.1-x86_64-disk
      rootVolume:
        diskSize: 1
        sourceType: "image"
        sourceUUID: d08b6b0f-361a-4586-860a-949b623abefa

---
I have to provide image: cirros-0.5.1-x86_64-disk and sourceUUID: d08b6b0f-361a-4586-860a-949b623abefa both otherwise following error reported


```
failed apply due to
```
error: error validating "capi-quickstart.yaml.external.good": error validating data: ValidationError(OpenStackMachineTemplate.spec.template.spec): missing required field "image" in io.x-k8s.cluster.infrastructure.v1alpha3.OpenStackMachineTemplate.spec.template.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

the cause is image should be `optional` and because if we go boot from volume, this field is optional
**What did you expect to happen:**

```
rootVolume:
        diskSize: 1
        sourceType: "image"
        sourceUUID: d08b6b0f-361a-4586-860a-949b623abefa
```

just above should work ,without the `image:`
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
