### ISSUE TITLE
Regression: Specifying subnet filter without network fails when it previously did not

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#993]
/kind bug

**What steps did you take and what happened:**
In OpenShift we add default networks to machines by subnet tag, e.g.:

```yaml
      networks:
      - filter: {}
        subnets:
        - filter:
            name: cluster-dsal-59p8x-nodes
            tags: openshiftClusterID=cluster-dsal-59p8x
```

This now returns an error. It previously succeeded.

**What did you expect to happen:**

We should find the requested subnet in any network, which was the previous behaviour.

**Anything else you would like to add:**

This was regressed by #935 in an interesting way. It turns out that the previous behaviour in this case was to list networks with an empty filter, which returns all networks, then execute a separate subnet query per-network and add all matches subnets. This worked, but was obviously also incredibly inefficient.

#935 was principally about adding a mock interface, but incidentally also modified GetSubnetsByFilter and GetNetworksByFilter to return an error if there were no results. This breaks us, because we're querying every network individually, but only one of them contains the subnet we're looking for. The first network we query which doesn't contain the target subnet will return an error.

I'm not 100% convinced this is a desirable change, but it did highlight a very inefficient use of the OpenStack REST API. We can address this just by making a more efficient API call.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): ac9c503a52d3c2311389fc549455e5abbdaa6a70
